### ISSUE TITLE
Error: The PERCY_TOKEN environment variable is missing

### ISSUE THREAD

**Issue by amowu** [percy/storybook-action#4]
I have added `PERCY_TOKEN` to the GitHub repo Settings > Secrets.

But I got a wrong results:

```
info => Output directory: /home/runner/work/hahow-design/hahow-design/storybook-static
/usr/local/bin/npx percy-storybook
Error:  Error: The PERCY_TOKEN environment variable is missing.
    at Object._callee$ (/home/runner/work/hahow-design/hahow-design/node_modules/@percy/storybook/lib/cli.js:84:19)
    at tryCatch (/home/runner/work/hahow-design/hahow-design/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/home/runner/work/hahow-design/hahow-design/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.<computed> [as next] (/home/runner/work/hahow-design/hahow-design/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/home/runner/work/hahow-design/hahow-design/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/runner/work/hahow-design/hahow-design/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
    at new F (/home/runner/work/hahow-design/hahow-design/node_modules/core-js/library/modules/_export.js:36:28)
    at Object.<anonymous> (/home/runner/work/hahow-design/hahow-design/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)
    at Object.run (/home/runner/work/hahow-design/hahow-design/node_modules/@percy/storybook/lib/cli.js:143:17)
    at Object.<anonymous> (/home/runner/work/hahow-design/hahow-design/node_modules/@percy/storybook/bin/percy-storybook.js:4:4)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at /usr/local/lib/node_modules/npm/node_modules/libnpx/index.js:268:14
##[error]The process '/usr/local/bin/npx' failed with exit code 1
##[error]Node run failed with exit code 1
```

This is my config file:

```yml
name: Percy
on: [push, pull_request]
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install
        run: npm i
      - name: Percy Test
        uses: percy/storybook-action@v0.1.1
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
```
